### PR TITLE
Update jest2 to 24.3.0

### PR DESCRIPTION
**Pull request by ohnx**
Should fix the CI errors.

### CODE REVIEW

**Comment by ohnx** [comment]
Eek, travis is still failing!

**Comment by ohnx** [comment]
Fixed in #181, but both should be merged because this one covers the main repo, and the other one covers the dashboard.

**Comment by wolfy1339** [comment]
You updated the wrong one xD

**Comment by ohnx** [comment]
No but the tests pass now! Merge plz

**Comment by ohnx** [comment]
I had to add jest-util as a dep, but the tests do pass now. travis says they pass and I verified locally, too.

**Comment by wolfy1339** [comment]
Well, it certainly fixed them. But it's not the right thing.

jest proper needs to be bumped. No need for jest-util as a direct dependency
________________________________

**Comment by ohnx** [comment]
Ok, I will close this one then.

**Pull request closed without merging**
