### PR TITLE
React typescript

### PR DESCRIPTION
**Pull request by wolfy1339**

### CODE REVIEW

**Comment by handicraftsman** [comment]
Doesnt even build 😱

**Comment by wolfy1339** [comment]
Well it does, you just need to run TypeScript before.
________________________________

**Comment by handicraftsman** [comment]
Oh lol - no tests defined

**Comment by handicraftsman** [comment]
Feel free to merge if it works - i am not the one who should review. If you need a review, poke bwbellairs.

**Comment by wolfy1339** [comment]
@BWBellairs

**Pull request merged**
